---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
        args:
          - -w
      - id: go-build-mod
      - id: go-mod-tidy
      - id: go-test-mod
      - id: go-vet-mod
      - id: go-sec-mod
      - id: go-staticcheck-mod
      - id: go-critic
      - id: golangci-lint-mod

ci:
  autofix_prs: false
