---
name: build-on-tag-creation
run-name: Running build on ${{ github.ref_name }} ${{ github.ref_type }}
on:
  push:
    tags:
      - "**"

env:
  GOOS: linux
  GOARCH: amd64
  # net/http might need disabling CGO
  CGO_ENABLED: 0

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo
        run: echo "running on ${GITHUB_REF}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Fmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Dependencies
        run: go get .

      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Dependencies
        run: go get .

      - name: Build on tag ${{ vars.GITHUB_REF }}
        run: mkdir -p outputs/ && go build -ldflags "-extldflags '-static' -s -w" -a -o outputs/kibana_exporter_${GITHUB_REF}_${GOOS}_${GOARCH}

      - name: Upload build artefact
        uses: actions/upload-artifact@v3
        with:
          path: outputs/kibana_exporter_${{ env.GITHUB_REF }}_${{ env.GOOS }}_${{ env.GOARCH }}
          name: kibana_exporter_${{ env.GITHUB_REF }}_${{ env.GOOS }}_${{ env.GOARCH }}
